esphome:
    name: waage

#gekaufte hardware, zB
esp32:
    board: mhetesp32devkit

wifi:
    ap:
       ssid: "UEM Waage MealTrainer"
       password: !secret ap_pw 

logger:

web_server:
    ota: false
    local: true

sensor:
  - platform: hx711
    name: "uem waage"
    update_interval: 1s #tbd
    dout_pin: GPIO14
    clk_pin: GPIO12
    id: uem
    gain: 128
    filters:
      - calibrate_linear:
        - -112800 -> 0
        - +61900 -> 518
    unit_of_measurement: g